version: '2'
services:

  postgres:
    image: postgres:latest
    container_name: postgres_turismo
    environment:
      - POSTGRES_NAME=turismo
      - NEW_POSTGRES_NAME=turismo
      - POSTGRES_PASSWORD=turismo
      - POSTGRES_USER=turismo
      - POSTGRES_DB=turismo
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bot
    ports:
      - "5433:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@turismo.com.br
      - PGADMIN_DEFAULT_PASSWORD=turismo_pass

  web:
    image: turismo:latest
    build: .
    container_name: turismo
    env_file:
      - .env
    environment:
      - NEW_POSTGRES_NAME=turismo
      - POSTGRES_USER=turismo
      - POSTGRES_PASSWORD=turismo
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "80:8000"
    volumes:
      - .:/srv
    depends_on:
      - postgres
