version: '3'

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=turismo
      - POSTGRES_USER=turismo
      - POSTGRES_DB=turismo
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bot
    ports:
      - "5433:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@turismo.com.br
      - PGADMIN_DEFAULT_PASSWORD=turismo_pass
