# Generated by Django 3.1.3 on 2020-11-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Nome da categoria')),
                ('slug', models.CharField(max_length=155, verbose_name='SLUG')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, verbose_name='Nome da cidade')),
                ('slug', models.CharField(max_length=155, verbose_name='SLUG')),
                ('state', models.CharField(max_length=40, verbose_name='Estado')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='Nome do País')),
                ('slug', models.CharField(max_length=155, verbose_name='SLUG')),
                ('country_code', models.IntegerField()),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Vitrines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255, verbose_name='Nome do hotel')),
                ('slug', models.CharField(max_length=155, verbose_name='SLUG')),
                ('image', models.URLField(verbose_name='URL Imagem')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrines.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrines.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrines.country')),
            ],
            options={
                'db_table': 'vitrines',
            },
        ),
    ]
