# Generated by Django 3.1.3 on 2020-11-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0002_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='neighborhood',
        ),
    ]
