# Generated by Django 3.1.3 on 2020-11-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0003_remove_city_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.TextField(verbose_name='Descrição sobre o hotel.')),
            ],
            options={
                'db_table': 'about',
            },
        ),
    ]
