# Generated by Django 3.1.3 on 2020-11-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0004_sobre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sobre',
            new_name='About',
        ),
    ]
